namespace Naucera.Iambic
{
	/// <summary>
	/// Abstract implementation of a parser grammar construct.
	/// </summary>
	/// 
	/// <remarks>
	/// <para>Copyright (C) 2010 by Amanda Koh.</para>
	/// </remarks>

	public abstract class GrammarConstruct
	{
		readonly string mName;
		TokenProcessorDelegate mProcessor;


		protected GrammarConstruct(string name)
		{
			mName = name;
		}


		/// <summary>
		/// Flag indicating whether a processor has been set for this construct.
		/// </summary>

		public bool HasProcessor {
			get { return mProcessor != null; }
		}


		public string Name {
			get { return mName; }
		}


		internal object ProcessToken(Token token, ParseContext context, params object[] args)
		{
			if (mProcessor == null)
				return null;

			return mProcessor(token, context, args);
		}


		/// <summary>
		/// Sets the processor delegate to use for handling tokens generated by
		/// this grammar construct, disabling token processing if null is
		/// specified.
		/// </summary>
		/// 
		/// <param name="processor">
		/// Delegate to handle output, or null.</param>
		/// 
		/// <returns>
		/// This grammar construct.</returns>

		public GrammarConstruct ReplacingMatchesWith(TokenProcessorDelegate processor)
		{
			mProcessor = processor;
			return this;
		}
	}
}
